[versions]
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.13.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
sdpAndroid = "1.1.1"
shimmer = "0.5.0"
lottie = "6.7.1"
retrofit = "3.0.0"
glide = "5.0.7"
compiler = "5.0.7"
playServicesAds = "24.7.0"
facebook = "6.21.0.0"
audienceNetworkSdk = "6.21.0"
lifecycleProcess = "2.10.0"
firebaseBom = "34.12.0"
firebaseCrashlytics = "18.6.1"
firebaseMessaging = "23.4.1"
userMessagingPlatform = "3.2.0"
installreferrer = "2.2"
agp = "8.13.2"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
facebook = { module = "com.google.ads.mediation:facebook", version.ref = "facebook" }
audience-network-sdk = { module = "com.facebook.android:audience-network-sdk", version.ref = "audienceNetworkSdk" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
user-messaging-platform = { module = "com.google.android.ump:user-messaging-platform", version.ref = "userMessagingPlatform" }
installreferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "installreferrer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }